# Generated by Django 4.0.2 on 2022-04-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_credentials_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('cs101', models.CharField(max_length=6)),
                ('cs102', models.CharField(max_length=6)),
                ('cs140', models.CharField(max_length=6)),
                ('mth120', models.CharField(max_length=6)),
                ('hw1', models.CharField(max_length=6)),
                ('test1', models.CharField(max_length=6)),
                ('hw3', models.CharField(max_length=6)),
                ('test2', models.CharField(max_length=6)),
                ('final', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PredictPrior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('cs101', models.FloatField()),
                ('cs102', models.FloatField()),
                ('cs140', models.FloatField()),
                ('mth120', models.FloatField()),
            ],
        ),
    ]
